# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Covariance Matrix
#'
#' This function computes the covariance matrix. It can compute the covariance matrix of a single matrix or the covariance between two matrices.
#' @param x A numeric matrix.
#' @param y An optional second numeric matrix to compute the covariance with. If not provided, the function computes the covariance of `x`.
#' @return A numeric matrix representing the covariance matrix.
#' @examples
#' mat1 <- matrix(1:4, nrow = 2)
#' mat2 <- matrix(1:6, nrow = 2)
#' covarianceMatrix(mat1)
#' covarianceMatrix(mat1, mat2)
#' @export
covarianceMatrix <- function(x, y = NULL) {
    .Call('_hw3cca_covarianceMatrix', PACKAGE = 'hw3cca', x, y)
}

#' Compute Eigenvalues
#'
#' This function computes the eigenvalues of a given matrix. It returns the eigenvalues in descending order.
#' @param mat A numeric matrix (arma::mat) for which to compute the eigenvalues.
#' @return A numeric vector (arma::vec) containing the eigenvalues in descending order.
#' @examples
#' mat <- matrix(c(2, -1, -1, 2), nrow = 2)
#' eigenValues(mat)
#' @export
eigenValues <- function(mat) {
    .Call('_hw3cca_eigenValues', PACKAGE = 'hw3cca', mat)
}

#' Matrix Multiplication
#'
#' Multiplies two matrices. The number of columns in the first matrix must match the number of rows in the second matrix.
#' @param mat1 A numeric matrix.
#' @param mat2 A numeric matrix.
#' @return A numeric matrix that is the result of multiplying `mat1` by `mat2`.
#' @examples
#' mat1 <- matrix(1:4, nrow = 2)
#' mat2 <- matrix(1:6, nrow = 2)
#' matrixMultiply(mat1, mat2)
#' @export
matrixMultiply <- function(mat1, mat2) {
    .Call('_hw3cca_matrixMultiply', PACKAGE = 'hw3cca', mat1, mat2)
}

#' Compute the Square Root of a Matrix
#'
#' This function computes the square root of a given square matrix using eigenvalue decomposition.
#' @param m A square numeric matrix (arma::mat).
#' @return A numeric matrix (arma::mat) that is the square root of the input matrix.
#' @examples
#' mat <- matrix(c(4, 0, 0, 4), nrow = 2)
#' matrixSqrtcpp(mat)
#' @export
matrixSqrtcpp <- function(m) {
    .Call('_hw3cca_matrixSqrtcpp', PACKAGE = 'hw3cca', m)
}

#' Scale a Matrix
#'
#' This function centers and scales a numeric matrix.
#' @param x A numeric matrix.
#' @return A scaled numeric matrix.
#' @export
#' @examples
#' scaleC(matrix(1:4, nrow = 2))
scaleC <- function(x) {
    .Call('_hw3cca_scaleC', PACKAGE = 'hw3cca', x)
}

#' Compute the Inverse of a Matrix
#'
#' This function computes the inverse of a given numeric matrix using the Armadillo library.
#' @param x A numeric matrix (NumericMatrix).
#' @return A numeric matrix (NumericMatrix) that is the inverse of the input matrix.
#' @examples
#' mat <- matrix(c(4, 7, 2, 6), nrow = 2)
#' solveMatrixcpp(mat)
#' @export
solveMatrixcpp <- function(x) {
    .Call('_hw3cca_solveMatrixcpp', PACKAGE = 'hw3cca', x)
}

#' Singular Value Decomposition
#'
#' This function performs a singular value decomposition on a given numeric matrix using the Armadillo library.
#' @param X A numeric matrix (arma::mat) for which the SVD is to be computed.
#' @return A list containing the matrices U, S, and V from the SVD.
#' @examples
#' mat <- matrix(c(1, 2, 3, 4), nrow = 2)
#' svdDecomposition(mat)
#' @export
svdDecomposition <- function(X) {
    .Call('_hw3cca_svdDecomposition', PACKAGE = 'hw3cca', X)
}

